[GCC]drivers/usb/typec/google: tcpci_fusb307: Fix missing return type
Reported by GCC 12.2.0

../drivers/usb/typec/tcpm/google/tcpci_fusb307.c:212:8: error: return type defaults to 'int' [-Werror=return-type]
  212 | static enable_load_switch(struct fusb307b_plat *chip)

Signed-off-by: Panchajanya1999 <kernel@panchajanya.dev>
(cherry picked from commit d24109f774ff73cb772c80cc6b07d19047aff213)
(cherry picked from commit e8ce2aeccbf8fdb515500cea680b46523c61be8b)
(cherry picked from commit 688243f4fa0b37895923ce9193d164781505e383)