[GCC]drivers/soc/google: pt: Fix no return statement
Reported by GCC 12.2

../drivers/soc/google/pt/pt.c:272:1: error: no return statement in function returning non-void [-Werror=return-type]
  272 | }
      | ^

Signed-off-by: Panchajanya1999 <kernel@panchajanya.dev>
(cherry picked from commit 97c8a54834525057b573655e5d9d3947ba2da129)
(cherry picked from commit e75642842c56a9617cf4588fa8230f445db843a7)
(cherry picked from commit 83b0fcd78e7b1c8d049772e3deec019ea9b8cd6b)